// Use local OpenAPI spec file generated by API
module.exports = {
  api: {
    input: '../api/swagger/openapi.json',
    output: {
      clean: true,
      prettier: true,
      target: './src/api/generated/api.ts',
      schemas: './src/api/generated/models',
      client: 'react-query',
      override: {
        mutator: {
          path: './src/api/customInstance.ts',
          name: 'customInstance',
        },
      },
    },
  },
};
