import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Klippli Privacy Policy. How we collect, use, and protect your data.",
  alternates: {
    canonical: '/privacy',
  },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors mb-12"
        >
          &larr; Back to home
        </Link>

        <h1 className="text-3xl font-bold tracking-tight mb-2">
          Privacy Policy
        </h1>
        <p className="text-sm text-muted-foreground mb-12">
          Last updated: November 25, 2025
        </p>

        <article className="prose prose-invert prose-sm max-w-none [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:mt-6 [&_h3]:mb-3 [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_li]:text-muted-foreground [&_ul]:space-y-1">
          <h2>General</h2>
          <p>
            Klippli (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;)
            commits to protecting privacy. This Policy explains how personal
            information is collected, used, and disclosed by Klippli.
          </p>
          <p>
            This Policy applies to the website, subdomains (collectively,
            &ldquo;Service&rdquo;) and Klippli application. By accessing or
            using the Service, you signify that you have read, understood, and
            agree to the collection, storage, use, and disclosure of your
            personal information as described in this Privacy Policy and Terms of
            Service.
          </p>

          <h2>Definitions and Key Terms</h2>
          <ul className="list-disc pl-5">
            <li>
              <strong className="text-foreground">Cookie:</strong> Small data
              amount generated by a website and saved by web browser to identify
              your browser, provide analytics, and remember preferences or login
              information.
            </li>
            <li>
              <strong className="text-foreground">Company:</strong> PE Livshits
              Ilia Aleksandrovich, 1 Leo St, 85, Yerevan, 0015&mdash;responsible
              for information under this Policy.
            </li>
            <li>
              <strong className="text-foreground">Country:</strong> Armenia,
              where Klippli or its owners/founders are based.
            </li>
            <li>
              <strong className="text-foreground">Customer:</strong> Company,
              organization, or person that signs up to use Klippli Service.
            </li>
            <li>
              <strong className="text-foreground">Device:</strong> Any
              internet-connected device (phone, tablet, computer) used to visit
              Klippli.
            </li>
            <li>
              <strong className="text-foreground">IP address:</strong> Number
              assigned to every device connected to the Internet.
            </li>
            <li>
              <strong className="text-foreground">Personnel:</strong> Individuals
              employed by Klippli or under contract to perform services.
            </li>
            <li>
              <strong className="text-foreground">Personal Data:</strong> Any
              information allowing identification or identifiability of a natural
              person.
            </li>
            <li>
              <strong className="text-foreground">Service:</strong> Service
              provided by Klippli as described in terms and on this platform.
            </li>
            <li>
              <strong className="text-foreground">
                Third-party service:
              </strong>{" "}
              Advertisers, sponsors, promotional partners, and others providing
              content or products.
            </li>
            <li>
              <strong className="text-foreground">Website:</strong>{" "}
              Klippli&apos;s site accessible via klippli.com.
            </li>
            <li>
              <strong className="text-foreground">You:</strong> Person or entity
              registered with Klippli to use the Services.
            </li>
          </ul>

          <h2>What Information Do We Collect?</h2>
          <p>
            Information is collected when you visit the website, register, place
            an order, subscribe to newsletter, respond to surveys, or fill out
            forms:
          </p>
          <ul className="list-disc pl-5">
            <li>Name / Username</li>
            <li>Email Addresses</li>
            <li>Mailing Addresses</li>
          </ul>

          <h2>How Do We Use The Information We Collect?</h2>
          <p>Collected information may be used for:</p>
          <ul className="list-disc pl-5">
            <li>Personalizing your experience</li>
            <li>Improving the website</li>
            <li>Improving customer service</li>
            <li>Processing transactions</li>
            <li>
              Administering contests, promotions, surveys, or site features
            </li>
            <li>Sending periodic emails</li>
          </ul>

          <h2>Use of Information from Third Parties</h2>
          <p>
            Klippli collects End User Data necessary to provide services to
            customers. End users may voluntarily provide information made
            available on social media websites.
          </p>
          <p>
            Some information comes from third parties when you contact Klippli.
            For example, when submitting an email address to show interest in
            becoming a customer, Klippli receives information from a third party
            providing automated fraud detection services. Klippli occasionally
            collects information made publicly available on social media
            websites.
          </p>

          <h2>Do We Share the Information We Collect with Third Parties?</h2>
          <p>
            Klippli may share collected information (personal and non-personal)
            with third parties including advertisers, contest sponsors,
            promotional and marketing partners, and others providing content or
            products of potential interest. Information may also be shared with
            current and future affiliated companies and business partners. In
            merger, asset sale, or business reorganization scenarios, personal
            and non-personal information may be shared or transferred to
            successors-in-interest.
          </p>
          <p>
            Klippli engages trusted third-party service providers for functions
            including server hosting, website maintenance, database storage and
            management, email management, storage marketing, credit card
            processing, customer service, and order fulfillment. Personal
            information, and possibly some non-personal information, will likely
            be shared with these third parties to enable service performance.
          </p>
          <p>
            Klippli may share log file data portions, including IP addresses,
            with third parties (web analytics partners, application developers,
            ad networks) for analytics purposes. Shared IP addresses may estimate
            general location and other technographics. Personal and non-personal
            information may be disclosed to government or law enforcement
            officials or private parties as Klippli, in its sole discretion,
            deems necessary or appropriate to respond to claims, legal process
            (including subpoenas), protect rights and interests of Klippli or
            third parties, ensure public or person safety, prevent or stop
            illegal, unethical, or legally actionable activity, or comply with
            applicable court orders, laws, rules, and regulations.
          </p>

          <h2>Where and When Is Information Collected?</h2>
          <p>
            Klippli collects personal information that you submit. Personal
            information may also be received from third parties as described
            above.
          </p>

          <h2>How Do We Use Your Email Address?</h2>
          <p>
            By submitting your email address on this website, you agree to
            receive emails from Klippli. Participation in email lists may be
            cancelled anytime by clicking the opt-out link or unsubscribe option
            included in the respective email. Emails are only sent to people who
            have authorized contact, either directly or through a third party.
            Klippli does not send unsolicited commercial emails.
          </p>
          <p>
            Email addresses submitted only through the order processing page will
            be used solely for sending information and updates pertaining to your
            order. If the same email was provided through another method, it may
            be used for any purposes stated in this Policy.
          </p>

          <h2>How Long Do We Keep Your Information?</h2>
          <p>
            Information is kept only as long as needed to provide Klippli and
            fulfill purposes described in this policy. When information is no
            longer needed and no legal or regulatory compliance requirement
            exists, it will be removed from systems or depersonalized so you
            cannot be identified.
          </p>

          <h2>How Do We Protect Your Information?</h2>
          <p>
            Klippli implements various security measures to maintain personal
            information safety when you place an order or enter, submit, or
            access personal information. A secure server is offered. All supplied
            sensitive/credit information is transmitted via SSL technology and
            encrypted into payment gateway provider databases, accessible only to
            those with special access rights required to keep information
            confidential. After transactions, private information is never kept
            on file. However, Klippli cannot ensure or warrant absolute security
            of any transmitted information.
          </p>

          <h2>International Transfers</h2>
          <p>
            Klippli is incorporated in Armenia. Information collected via
            website, direct interactions, or help services may be transferred to
            Klippli offices or personnel, or to third parties, located throughout
            the world, and may be viewed and hosted anywhere globally.
          </p>

          <h2>Your Rights and Choices</h2>
          <p>
            Rights to request updates or corrections to information Klippli
            collects depend on your relationship with Klippli. Customers can
            request to update, correct, restrict, or delete their personal data.
            Klippli may take reasonable steps to verify identity before granting
            profile access or making corrections.
          </p>

          <h2>Personnel</h2>
          <p>
            If you are a Klippli worker or applicant, information you voluntarily
            provide is collected. Collected information is used for Human
            Resources purposes to administer benefits to workers and screen
            applicants.
          </p>

          <h2>Sale of Business</h2>
          <p>
            Klippli reserves the right to transfer information to a third party
            in event of a sale, merger, or transfer of all or substantially all
            Klippli assets or Corporate Affiliate assets, or if Klippli
            discontinues business or enters bankruptcy or similar proceedings,
            provided the third party agrees to adhere to this Privacy Policy
            terms.
          </p>

          <h2>Affiliates</h2>
          <p>
            Information (including personal information) about you may be
            disclosed to Corporate Affiliates. Information provided to Corporate
            Affiliates will be treated in accordance with this Privacy Policy.
          </p>

          <h2>Governing Law</h2>
          <p>
            This Privacy Policy is governed by Armenian law without regard to
            conflict of laws provisions. You consent to exclusive court
            jurisdiction for any action or dispute arising under or in connection
            with this Privacy Policy.
          </p>

          <h2>Your Consent</h2>
          <p>
            This Privacy Policy has been updated to provide complete transparency
            into what is set when you visit the site and how it is used. By using
            the website, registering an account, or making a purchase, you
            consent to this Privacy Policy and agree to its terms.
          </p>

          <h2>Links to Other Websites</h2>
          <p>
            This Privacy Policy applies only to the Services. The Services may
            contain links to other websites not operated or controlled by
            Klippli. Klippli is not responsible for content, accuracy, or
            opinions expressed in such websites. Your browsing and interaction on
            any other website is subject to that website&apos;s own rules and
            policies.
          </p>

          <h2>Cookies</h2>
          <p>
            Klippli uses &ldquo;Cookies&rdquo; to identify areas of the website
            that you have visited. Most web browsers can be set to disable Cookie
            use. However, disabling Cookies may prevent correct website
            functionality or access. Klippli never places Personally
            Identifiable Information in Cookies.
          </p>

          <h2>Blocking and Disabling Cookies</h2>
          <p>
            You may set your browser to block cookies and similar technologies,
            but this may block essential cookies and prevent proper website
            functioning. Disabling a cookie or cookie category does not delete it
            from your browser; you must do this yourself within your browser.
          </p>

          <h2>Payment Details</h2>
          <p>
            Regarding any credit card or payment processing details provided,
            Klippli commits to storing this confidential information in the most
            secure manner possible.
          </p>

          <h2>Kids&apos; Privacy</h2>
          <p>
            Klippli does not address anyone under age 13. Klippli does not
            knowingly collect personally identifiable information from anyone
            under age 13.
          </p>

          <h2>Changes To Our Privacy Policy</h2>
          <p>
            Klippli may change its Service and policies, necessitating Privacy
            Policy changes to accurately reflect Service and policies. Unless
            otherwise required by law, Klippli will notify you (for example,
            through the Service) before making changes and give you an
            opportunity to review them before they go into effect.
          </p>

          <h2>Third-Party Services</h2>
          <p>
            Klippli may display, include, or make available third-party content
            (data, information, applications, and other products/services) or
            provide links to third-party websites or services
            (&ldquo;Third-Party Services&rdquo;). You acknowledge and agree that
            Klippli shall not be responsible for any Third-Party Services.
          </p>

          <h2>Information About GDPR</h2>
          <p>
            For individuals from the European Economic Area (EEA), this section
            explains how and why your data is collected and how it is maintained
            under protection.
          </p>

          <h3>What Is Personal Data?</h3>
          <p>
            Any data relating to an identifiable or identified individual.
            Examples include financial information, political opinions, genetic
            data, biometric data, IP addresses, physical address, sexual
            orientation, and ethnicity.
          </p>

          <h3>Data Protection Principles</h3>
          <ul className="list-disc pl-5">
            <li>Processed in a fair, legal, and transparent way.</li>
            <li>
              Collected for a specific purpose and only used for that purpose.
            </li>
            <li>
              Held no longer than necessary to fulfill its purpose.
            </li>
            <li>
              Individuals have the right to access, copy, update, delete,
              restrict, or move their data.
            </li>
          </ul>

          <h2>Contact Us</h2>
          <p>
            For questions, contact us at{" "}
            <a
              href="mailto:support@klippli.com"
              className="text-primary hover:underline"
            >
              support@klippli.com
            </a>
            .
          </p>
        </article>
      </div>
    </div>
  );
}
